### ISSUE TITLE
New "why testing" explanation

### ISSUE THREAD

**Issue by felix91gr** [felix91gr/awesome-system-swift#18]
Tangent of #17 

Having the `<details>` HTML tag available allows us to be more descriptive of why we require tests in libraries before listing them. The idea here is to come up with a better explanation, now that we don't have the limitation of space.

**This is the current explanation:**

> Why are tests required for libraries? Libraries, unlike apps, can't be run to check that they work as intended. Therefore, tests are essential to maintain them. Tests are also very convenient to check that they work on all supported platforms.

**Comment by felix91gr** [comment]
What about this to start with?

<details>
<summary>Why are tests required for libraries?</summary>

* Unlike apps, libraries **can't be run** to check if they work as intended. They have to be used in a program or checked by a test suite.
* In general, testing will be **more exhaustive** than usage.
* Testing can also be **automated**.
* It also can be run on **many platforms** at once, which helps in keeping compatibility with all the intended users of the library. 
</details>

---

Pardon my writing, I'm pretty sure it can use some polish. I've been running and am quite tired, but I prefer to get this thread started today :slightly_smiling_face:

At least it's just a starting point :P

**Comment by vknabel** [comment]
Sorry for the late response.
I think most points are good to go. When reading through all points, the last one seems a bit verbose in contrast to the others. I think just removing the last part would solve this.

> It also can be run on many platforms at once, which helps in keeping compatibility. 

What do you think?

**Comment by felix91gr** [comment]
I agree. I also think my wording is a bit ambiguous on "run on many different platforms at once". I read it now and I thought: _"Does that mean that you run them on parallel or something?"_

How about this:

> Tests can be set up to **run on different** platforms. This helps in keeping **compatibility**.

**Comment by vknabel** [comment]
Yes you are right. The second version is definitely clearer.

Shall we add the way how to automate testing? 
> Testing can be **automated** using continuous integration.

**Comment by felix91gr** [comment]
Oh, I was thinking of testing automation in general. As in for example, how a script runs your testing suites locally, as well as how CI always checks that your commits are passing before merging.

But automation is stronger in CI, since it's 100% automated. Unlike having to type `swift test` to run the project's test suites, CI _just triggers_. We might want to explicitly point out that systems like CI exist. I think it's a good idea.

**Comment by felix91gr** [comment]
Alright, I think this is the definitive one then: 

<details>
<summary>Why are tests required for libraries?</summary>

* Unlike apps, libraries **can't be run** to check if they work as intended. They have to be used in a program or checked by a test suite.
* In general, testing will be **more exhaustive** than usage.
* Testing can also be **automated** using continuous integration.
* Tests can be set up to **run on different** platforms. This helps in keeping **compatibility**.
</details>

I'll put it on a PR now :)
