### ISSUE TITLE
Does TraceLog belong to a specific category?

### ISSUE THREAD

**Issue by felix91gr** [felix91gr/awesome-system-swift#26]
I was reading the index and this jumped out at me. "Logging" seems like a very specific category, and maybe it could be moved into a more general one and maybe be reworded as well.

I'd say that logging is a kind of workflow, and therefore it would go under the **Workflow-enabler Frameworks** section.

But apart from that, is "Logging" itself a workflow, or is it part of a more general thing? Like how asyncronous and reactive programming are part of the same family. I was thinking that maybe that category would be:

#### Logging and Tracing

or something like that.

Thoughts? @tonystone @vknabel 
I've never used logging extensively, so I'm out of my knowledge here. Where does logging belong?

---

Also, related to this. @tonystone: does TraceLog do tracing? In the sense that [uftrace](https://github.com/namhyung/uftrace) does "tracing"? Or is it in this context, an alternative word for logging?

**Comment by tonystone** [comment]
Hi @felix91gr, sorry for the delay.  Yes, that makes sense, you could also use "Logging and Tracing" as well which I think would be proper.

**Comment by felix91gr** [comment]
Yeah, that makes sense to me as well. Wikipedia, after all, makes an [explicit point](https://en.wikipedia.org/wiki/Tracing_(software)#Event_logging_versus_tracing) about what exactly separates Logging from Tracing. They seem to be close enough to each other, and I'll take your word for it :slightly_smiling_face: 

I'll issue a PR with a draft.

**Comment by felix91gr** [comment]
Completed at #27 :)
