### ISSUE TITLE
Thoughts on Workspace?

### ISSUE THREAD

**Issue by SDGGiesbrecht** [felix91gr/awesome-system-swift#3]
[Workspace](https://github.com/SDGGiesbrecht/Workspace#workspace) has no stable release compatible with Swift 4.1 yet; the last stable release works with Swift 4.0.3.

But Workspace is still usable with Swift 4.1 when built from source on its `swift‐4.1` branch. (It is unrelated parts of dependencies that delay their release and force Workspace to link against their branches instead of stable versions.) Just use it only from the command line for now, because the scripts mentioned in the read‐me will try to retrieve the stable version and fail to compile under Swift 4.1.

There are many changes and improvements already on the to‐do list, but I would be interested to know what you think.

**Comment by vknabel** [comment]
Merged in #16
